version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: siapee_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Analinda
      POSTGRES_DB: siapee
    ports:
      - '5432:5432'
    volumes:
      - siapee_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: siapee_pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: Analinda
    ports:
      - '8081:80'

volumes:
  siapee_pgdata:
